//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.11.04 at 18:52:22 PM MSK
//

package com.dsu.arslan.coursework.ws.genres;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.dsu.arslan.coursework.ws.genres package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dsu.arslan.coursework.ws.genres
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetGenresRequest }
     *
     */
    public GetGenresRequest createGetGenresRequest() {
        return new GetGenresRequest();
    }

    /**
     * Create an instance of {@link GetGenresResponse }
     *
     */
    public GetGenresResponse createGetGenreResponse() {
        return new GetGenresResponse();
    }

    /**
     * Create an instance of {@link GenresWS }
     *
     */
    public GenresWS createGenresWS() {
        return new GenresWS();
    }

}
