CREATE ROLE student WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:3qzWRmpk4iQ5X7B8yV0MGw==$qCqPtnBT0KjPcMzrAWD8QctBCj1sCkSOqSDaeSiln90=:pAjBlrZewuxl1D2bCPHNT4h5HpzzlQUu/7ozxjMkWzg=';
